SET (POT_FILE fdupves.pot)
SET (PO_FILES fdupves.po)
SET (GMO_FILES zh_CN.gmo)
SET (SRC_PO_FILES ${CMAKE_CURRENT_SOURCE_DIR}/fdupves.po)

FILE(GLOB_RECURSE SRCS "${CMAKE_SOURCE_DIR}/src/*.c")
STRING(REPLACE ";" "\n" SRCS_STR "${SRCS}")
FILE(WRITE "${CMAKE_CURRENT_BINARY_DIR}/cfiles" "${SRCS_STR}")

IF(WIN32)
  FindPackage(Gettext)
ELSE()
  SET(GETTEXT_XGETTEXT_EXECUTABLE xgettext)
  SET(GETTEXT_MSGMERGE_EXECUTABLE msgmerge)
  SET(GETTEXT_MSGFMT_EXECUTABLE msgfmt)
ENDIF()

ADD_CUSTOM_COMMAND (COMMAND ${GETTEXT_XGETTEXT_EXECUTABLE}
  -f cfiles
  -k_
  -o ${POT_FILE}
  OUTPUT ${POT_FILE}
  DEPENDS ${SRCS} "${CMAKE_CURRENT_BINARY_DIR}/cfiles")

ADD_CUSTOM_TARGET (pofiles COMMAND ${GETTEXT_MSGMERGE_EXECUTABLE}
  --force-po
  ${SRC_PO_FILES} ${POT_FILE}
  -o ${PO_FILES}
  DEPENDS ${POT_FILE})

ADD_CUSTOM_TARGET (gmofiles ALL COMMAND ${GETTEXT_MSGFMT_EXECUTABLE}
  -o ${GMO_FILES}
  ${PO_FILES}
  DEPENDS ${PO_FILES})

INSTALL (FILES ${CMAKE_CURRENT_BINARY_DIR}/${GMO_FILES}
  DESTINATION share/locale/zh_CN/LC_MESSAGES
  RENAME fdupves.mo)

ADD_DEPENDENCIES(gmofiles pofiles)
