name: Build

on:
  push:
    branches: [ "master", "feat*" ]
  pull_request:
    branches: [ "master", "feat*" ]

jobs:
  build-linux:
    name: Fedora 43 Build
    runs-on: ubuntu-latest
    container: fedora:43
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          dnf install -y gcc-c++ cmake ninja-build git pkgconf-pkg-config gtk3-devel ffmpeg-free-devel opencv-devel mupdf-devel rpm-build gettext

      - name: Build by cmake
        run: |
          cmake -B build -S . -DCMAKE_BUILD_TYPE=Release --verbose
          cmake --build build --verbose
          cd build
          cpack -G RPM --verbose

  build-windows:
    name: Windows 11 Build
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build with script
        run: ./windows-build.ps1
